import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: 'Nova Developers',
    description: 'Generated by create next app',
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
    return (
        <html lang="en">
        <head>
            <title>Nova Developers</title>
            <link rel="icon" href="/img/icon.ico" title="Favicon"/>
        </head>
        <body className={inter.className}>{children}</body>
        </html>
    )
}

export default RootLayout;
