import type {Metadata} from "next";
import Header from "./components/Header";
import {Montserrat} from "next/font/google";
import "./globals.css";
import React from "react";
import Footer from "@/app/components/Footer/Footer";
import Container from "@/app/components/Container/Container";

const mont = Montserrat({subsets: ["latin"]});

interface RootLayoutProps {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: "Nova Developers",
    description: "Generated by create next app",
};

const RootLayout: React.FC<RootLayoutProps> = ({children}) => {
    return (
        <html lang="en">
        <head>
            <title>Nova Developers</title>
            <link rel="icon" href="/img/icon.ico" title="Favicon"/>
        </head>
        <body className={mont.className}>
        <Container>
            <Header/>
            <Footer/>
        </Container>
        {children}
        </body>
        </html>
    );
};

export default RootLayout;
